Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
  
    # VirtualBox設定
    config.vm.provider "virtualbox" do |vb|
      # メモリ設定
      vb.memory = "10240"
    end
  
    # シェルスクリプトでのプロビジョニング
    config.vm.provision "shell", inline: <<-SHELL
      # システムアップデート
      sudo apt update -y
  
      # Dockerのセットアップ
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      sudo systemctl enable docker
      sudo systemctl start docker
      sudo usermod -aG docker $USER
  
      # Docker Composeのセットアップ
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
  
      mkdir -p /home/vagrant/dev
      chown -R vagrant:vagrant /home/vagrant/dev
    SHELL
  
    # ポートの転送設定
    ports = {80 => 80, 8080 => 8080, 3000 => 3000, 3306 => 3306, 3307 => 3307, 5432 => 5432}
    ports.each do |guest, host|
      config.vm.network "forwarded_port", guest: guest, host: host
    end
  end
  